name: Trigger Netlify Build Daily
on:
  schedule:
    # Run at 03:00 daily
    - cron: '0 3 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6823adb96dd8fd3feb1b677f