name: Trigger Netlify Builds Daily
on:
  schedule:
    # Run at 03:00 daily
    - cron: '0 3 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Build hugohymascom
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/68329cca0cbfe51c2587aeb5

      - name: Build benkazezcom
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/68329c6817bab29aa45347e6